import AuthProvider from '@/component/AuthProvider'
import './globals.css'


export const metadata = {
  title: 'Ecommerce Admin',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
        {children}

        </AuthProvider>
      </body>
    </html>
  )
}
